/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import sample.grizzly.SampleGrizzlyApplication;
import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        SampleGrizzlyApplication classUnderTest = new SampleGrizzlyApplication();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
